### ISSUE TITLE
Update and improve documentation

### ISSUE THREAD

**Issue by alrra** [h5bp/html5-boilerplate#1554] opened 2014-07-03 19:49 UTC
- [x] `TOC.md` (done in 0efb9fb)
- [x] `crossdomain.md` (done in 3220cf1)
- [ ] `css.md` (partially done in 0443e50)
- [ ] `extend.md`  
  - [ ] Update documentation regarding touch icons (see https://github.com/h5bp/html5-boilerplate/pull/1664)
  - [ ] Add info on Yandex Themeing meta tags (see https://github.com/h5bp/html5-boilerplate/issues/1646)
  - [x] Add info on `theme-color` meta tag (done in 78c84ce70185ff0fc513957eb5f4270672b43a7e)
- [x] `faq.md` (done in 296b0bb & 8935453)
  - [x] Include information about the recent [jQuery announcement](http://blog.jquery.com/2014/07/03/dont-use-jquery-latest-js/) (done in 8935453)
- [ ] `html.md` (partially done in: 973b8453ded68af1d9c833d4ad4312e6c63ccbeb, 1cac1c9ecc1d3a2ebb4c6b107545ad6ec51d938e)
- [ ] `js.md`  
  - [x] Add information about script from `plugins.js`(done in 5027eea) 
- [ ] `misc.md`  
  - [x] Add information about  `/browserconfig.xml` and tile images (done in 001a6c9
    )
  - [x] Add information about `robots.txt` (done in: 3e3b770 , f134545)
  - [ ] Add information about `.htaccess` (partially done in: ff27f8c5)
  - [ ] Add information about the web application manifest file
- [x] `usage.md` (done in https://github.com/h5bp/html5-boilerplate/commit/2fcde1ef33d96349dd28f1c4a9909c9aec999ed9)

**Comment by kkirsche** [comment] 2015-01-09 14:55
I am interested in helping with this but would need a better idea of what type of content you would like these to contain. I see some are partially done, but don't specify what would be required to consider them fully complete. Let me know what you'd be interested in for the remaining pieces and I can put something together and send the equiv PRs

**Comment by arthurvr** [comment] 2015-01-09 16:29
@kkirsche We would love the have you contributing! All contributions are always welcome. Just FYI, this list of files that we really would like to get done before v5; in fact docs are never really finished, and we're open for all improvements.

As I said, I'm also having a hard time figuring out what really needs to be done. As I said, filenames are just filenames but that's not that helpful in here. Best workflow is to run through a file and its appropriate documentation and see what parts aren't being documented. We don't want to document every byte, but the specialities, best-practices and used techniques.

**Comment by ArthurSucksDicks** [comment] 2015-01-09 16:43
@arthurvr suck my dick you gay fuck!!!!

**Comment by alrra** [comment] 2015-03-05 12:28
>  As I said, I'm also having a hard time figuring out what really needs to be done. As I said, filenames are just filenames but that's not that helpful in here.

The basic idea is to just go through all the documentation related files and:

   * update anything that is outdated
   * add any missing content (e.g.: things that were added to H5BP, but were not documented)
   * simplify and make the existing content more consistent (e.g.: have kinda the same wording)
   * move things around to better organize the content and avoid repetition

**Comment by roblarsen** [comment] 2017-03-18 03:45
Add docs based on 

#1822 and #1783

**Comment by roblarsen** [comment] 2017-07-11 18:56
And... #1963 

@coliff  this issue outlines some additional documentation tasks. We don't need to get through everything for 6.0, but a good documentation pass with this in mind seems like a good idea.

**Comment by coliff** [comment] 2017-07-13 13:12
Cool. I'll work on getting a PR in for the webmanifest.

Also, I noticed that there isn't any mention about the `.gitattributes` file in the misc.md when there probably should be (`.gitignore` is mentioned there). I'm not too familiar with _exactly_ how that file works (though did skim-read the docs on the Git site about it: https://git-scm.com/docs/gitattributes).

**Comment by coliff** [comment] 2017-07-20 16:30
Doc changes left to do that I can think of....

**Usage**

- We suggest using a build script such as ant - maybe also suggest Gulp and Grunt as they are more popular?

**FAQ**

- Remove the ‘Google Analytics at the bottom’ FAQ as it is covered elsewhere in the docs.. Plus performance isn’t really an issue since it loads defer/async
- Remove the section on using Initializr since it isn’t maintained (the project owner confirmed to me today that it is being retired and turned off soon)
- Nicolas’ great post on Quora could be rewritten/updated and included as the FAQ answer to ‘How can I integrate Bootstrap with HTML5 Boilerplate?’

**Everything Else**

- Below the table of contents  change the ‘--’ to ‘---’ (the horizontal rule doesn’t render in Github markdown)
- Add ‘gitattributes’ documentation

**Extend**

- In the miscellaneous section include a link to the excellent resource of everything that could go in the `<head>` of your document: http://gethead.info .
- Chrome Mobile web apps section could possibly be removed since that section is covered by w3c manifest.
- Apple Touch icons section needs updating. No need to mention non-retina iPhone and iOS versions lower than iOS 6 for example. I'm not sure the best suggestion on what to include here, but Apple's docs just list 4 sizes now. (https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html)

**Comment by roblarsen** [comment] 2017-07-20 16:44
All good. Some comments:

>Remove the section on using Initializr since it isn’t maintained (the project owner confirmed to me today that it is being retired and turned off soon)

👍  I would add a note that we are going to add a command line utility that does some of what initializr offered to v7 (because that's a thing now, I guess, since I said it twice.) 

>Nicolas’ great post on Quora could be rewritten/updated and included as the FAQ answer to ‘How can I integrate Bootstrap with HTML5 Boilerplate?’

Summarize and link to it?

**Comment by roblarsen** [comment] 2017-07-20 17:09
>We suggest using a build script such as ant - maybe also suggest Gulp and Grunt as they are more popular?

That section needs a fuller rewrite. Creating a PR for that one.

**Comment by roblarsen** [comment] 2017-08-01 17:29
I'm going to close this because, honestly. I just want to get 6.0 out the door and we can continue to tweak the docs.

**Closed by roblarsen** 2017-08-01 17:29 UTC
Labels: documentation, help wanted
