### ISSUE TITLE
Consider adding a Web Manifest file to support "saving to homescreen"

### ISSUE THREAD

**Issue by elisechant** [h5bp/html5-boilerplate#1862] opened 2016-06-09 02:35 UTC
As a progressive enhancement, considering that h5bp supports favicons, I see that it should also support linking to a manifest.webmanifest file which would enable "save to homescreen" functionality and sensible defaults for meta associated with Web App (or website) such as name, description, icon etc.

index.html
`<link rel="manifest" href="manifest.webmanifest">`

manifest.webmanifest
```
{
  "lang": "en",
  "dir": "ltr",
  "name": "Super Racer 2000",
  "description": "The ultimate futuristic racing game from the future!",
  "short_name": "Racer2K",
  "icons": [{
    "src": "icon/lowres.webp",
    "sizes": "64x64",
    "type": "image/webp"
  },{
    "src": "icon/lowres.png",
    "sizes": "64x64"
  }, {
    "src": "icon/hd_hi",
    "sizes": "128x128"
  }],
  "scope": "/racer/",
  "start_url": "/racer/start.html",
  "display": "fullscreen",
  "orientation": "landscape",
  "theme_color": "aliceblue",
  "background_color": "red"
}
```

**Comment by 22923076** [comment] 2016-06-13 17:10
I also have a Alcatel One Touch A521L and I use straight talk services. How would I use tools such as this to stay connected?

**Comment by 22923076** [comment] 2016-06-13 17:11
I can't seem to have any luck with html

**Comment by paulirish** [comment] 2016-08-08 20:56
closing as dupe of #1629 

but yes we should do this

**Closed by paulirish** 2016-08-08 20:56 UTC
